# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: /images/tja_logo.svg

# index custom copy. edit these to change the copy
# hero
heroslogan: I build effective, user-friendly web experiences
# intro
customintro: true
# intro_title: Hello!
# intro_copy: Lorem ipsum dolsor sit amet
# posts
posts_title: Work & side projects
# outro
outro_title: Contact
outro_copy: Interested in working together? Complete and submit the form below to send me an email. Looking forward to hearing from you.
email_address: thomwork@gmail.com
email_buttontext: Email me
# footer
footer_copy: Built with the <a href="https://hexo.io/" title="Hexo">Hexo</a> blog framework and the <a href="https://github.com/tjallen/hexo-theme-tja" title="TJA hexo theme">tja theme</a>. Company logos and imagery are copyright of their respective owners.
github_user: tjallen
footer_github: true
contactform: true
# Default post title
default_post_title: Untitled

# Default post thumb index page (Recommended)
default_image_thumb: /images/blur-tilt.jpg

# Default post cover index page (Optional)
default_image_cover:
default_image_post:

# Show Dates for posts and pages
show_dates:

# Google Analytics Tracking ID
google_analytics:
